// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            uuid.UUID          `db:"id"`
	Name          string             `db:"name"`
	Email         string             `db:"email"`
	PasswordHash  *string            `db:"password_hash"`
	GoogleID      *string            `db:"google_id"`
	AvatarUrl     *string            `db:"avatar_url"`
	EmailVerified bool               `db:"email_verified"`
	CreatedAt     time.Time          `db:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at"`
}
