// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, google_id, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	Name         string  `db:"name"`
	Email        string  `db:"email"`
	PasswordHash *string `db:"password_hash"`
	GoogleID     *string `db:"google_id"`
	AvatarUrl    *string `db:"avatar_url"`
}

type CreateUserRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleID,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE google_id = $1 AND deleted_at IS NULL
`

type GetUserByGoogleIDRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (GetUserByGoogleIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i GetUserByGoogleIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListUsersRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.GoogleID,
			&i.AvatarUrl,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, password_hash = $4, google_id = $5, avatar_url = $6, email_verified = $7, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, password_hash, google_id, avatar_url, email_verified, created_at, updated_at
`

type UpdateUserParams struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
}

type UpdateUserRow struct {
	ID            uuid.UUID `db:"id"`
	Name          string    `db:"name"`
	Email         string    `db:"email"`
	PasswordHash  *string   `db:"password_hash"`
	GoogleID      *string   `db:"google_id"`
	AvatarUrl     *string   `db:"avatar_url"`
	EmailVerified bool      `db:"email_verified"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleID,
		arg.AvatarUrl,
		arg.EmailVerified,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
